### ISSUE TITLE
这里为啥是 image.shape[1]

### ISSUE THREAD

**Issue by zhijiejia** [CarnoZhao/Kaggle-UWMGIT#1]
![image](https://user-images.githubusercontent.com/43838913/169833072-74c43b91-12c8-4358-91ec-3ce164242c91.png)

请问 这里不应该是 ```for i in range(msks.shape[0]):``` 吗？

而且 这样保存的 mask的shape是（h, w, 3）对吗？ 为啥不合到一个通道上呢，为啥mask的shape不合成（h, w）呢？

**Comment by CarnoZhao** [comment]
Thanks for finding out this bug. 

Yes, this should be `range(msks.shape[0])`.
